[project]
name = "high-performance-work-cleaner"
authors = ["Performance Engineering Team"]
description = "A decentralized work performance tracking and incentivization system"
telemetry = false
requirements = []
[contracts.performance-tracker]
path = "contracts/performance-tracker.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
